name: pcb-analysis
channels: [conda-forge]
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - plotly
  - scikit-learn
  - rich
  - tqdm
  - open3d
  - trimesh
  - ipympl
