name: pcb-papnet
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.11.14
  - numpy
  - scipy
  - pyyaml
  - tqdm
  - pip
  - transforms3d
  - pip:
    - lie_learn
    - transforms3d
    - torch==2.8.0 --index-url https://download.pytorch.org/whl/cu126
    - torchvision==0.23.0 --index-url https://download.pytorch.org/whl/cu126