name: pcb-papnet
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.11.14
  - numpy
  - scipy
  - pyyaml
  - tqdm
  - pip
  - transforms3d
  - pip:
    - lie_learn
    - torch==2.6.0 --index-url https://download.pytorch.org/whl/cu118
    - torchvision==0.21.0 --index-url https://download.pytorch.org/whl/cu118
    - git+https://github.com/mariogeiger/se3cnn@546bc682887e1cb5e16b484c158c05f03377e4e9